language: node_js
node_js:
  - 11
script:
  - npm run deploy
cache:
  directories:
  - node_modules
# branch: master
branches:
  only:
    - master
install:
  - npm install
branch: master
notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=$TRAVIS_TOKEN
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  body: |
   Please refer to [CHANGELOG.md](https://github.com/lxchuan12/blog/blob/master/CHANGELOG.md) for details.
  on:
    tags: true
